/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/Mascot/Mascot.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Mascot = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./mascot/mascot.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="mascot">
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_TashiMascot001">
            <skinnedMesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['M_TashiMascot_Armor.002']} skeleton={nodes.Mesh001.skeleton} />
            <skinnedMesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['M_TashiMascot_Skin.002']} skeleton={nodes.Mesh001_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Mascot;

useGLTF.preload('./mascot/mascot.gltf')
