/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/mascot-v1/mascot.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Mascot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/mascot-v1/mascot.gltf')
  const { actions } = useAnimations(animations, group)

  console.log(materials); // Log the entire materials object
  console.log(Object.keys(materials)); 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Float">
          <primitive object={nodes.mixamorigHips}>
            <primitive object={nodes.mixamorigSpine}>
              <primitive object={nodes.mixamorigSpine1}>
                <primitive object={nodes.mixamorigSpine2}>
                  <primitive object={nodes.mixamorigNeck}>
                    <primitive object={nodes.mixamorigHead}>
                      <primitive object={nodes.mixamorigHeadTop_End}/>
                    </primitive>
                  </primitive>
                  <primitive object={nodes.mixamorigLeftShoulder}>
                    <primitive object={nodes.mixamorigLeftArm}>
                      <primitive object={nodes.mixamorigLeftForeArm}>
                        <primitive object={nodes.mixamorigLeftHand}>
                          <primitive object={nodes.mixamorigLeftHandIndex1}>
                            <primitive object={nodes.mixamorigLeftHandIndex2}>
                              <primitive object={nodes.mixamorigLeftHandIndex3}>
                                <primitive object={nodes.mixamorigLeftHandIndex4}>
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                  <primitive object={nodes.mixamorigRightShoulder}>
                    <primitive object={nodes.mixamorigRightArm}>
                      <primitive object={nodes.mixamorigRightForeArm}>
                        <primitive object={nodes.mixamorigRightHand}>
                          <primitive object={nodes.mixamorigRightHandIndex1}>
                            <primitive object={nodes.mixamorigRightHandIndex2}>
                              <primitive object={nodes.mixamorigRightHandIndex3}>
                                <primitive object={nodes.mixamorigRightHandIndex4}>
                    
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
              
            </primitive>
            <primitive object={nodes.mixamorigLeftUpLeg}>
              <primitive object={nodes.mixamorigLeftLeg}>
                <primitive object={nodes.mixamorigLeftFoot}>
                  <primitive object={nodes.mixamorigLeftToeBase}>
                    <primitive object={nodes.mixamorigLeftToe_End}>
                    
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
            </primitive>
            <primitive object={nodes.mixamorigRightUpLeg}>
              <primitive object={nodes.mixamorigRightLeg}>
                <primitive object={nodes.mixamorigRightFoot}>
                  <primitive object={nodes.mixamorigRightToeBase}>
                    <primitive object={nodes.mixamorigRightToe_End}>
                    
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
            </primitive>
    
          </primitive>
          <group name="Mesh002">
            <skinnedMesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials['M_TashiMascot_Armor.001']} skeleton={nodes.Mesh002_1.skeleton} frustumCulled={false}/>
            <skinnedMesh name="Mesh002_2" geometry={nodes.Mesh002_2.geometry} material={materials['M_TashiMascot_Skin.001']} skeleton={nodes.Mesh002_2.skeleton} frustumCulled={false}/>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mascot-v1/mascot.gltf')
