/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/test2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Test2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/test2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Float">
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_TashiMascot002" />
          <group name="Mesh002">
            <skinnedMesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials['M_TashiMascot_Armor.001']} skeleton={nodes.Mesh002_1.skeleton} />
            <skinnedMesh name="Mesh002_2" geometry={nodes.Mesh002_2.geometry} material={materials['M_TashiMascot_Skin.001']} skeleton={nodes.Mesh002_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/test2.glb')
